### ISSUE TITLE
ONT read with multiple barcode

### ISSUE THREAD

**Issue by ashokpatowary** [pachterlab/splitcode#25]
Hi @Yenaled 

I have a basic question about application of split code with long read. In the example you design the config file as 
```
@extract <umi[10]>8{linker1},<bc[8]>{linker1},{linker1}<bc[8]>{linker2},{linker2}<bc[8]>,{linker2}8<read>0:-1
tags                            ids      distances  minFinds  maxFinds  locations  next
GTGGCCGATGTTTCGCATCGGCGTACGACT  linker1  2          1         1         0:18       {linker2}8-8
ATCCACGTGCTTGAGACTGTGG*          linker2  2          1         1         0      -
```

However, if I want the barcodes matched to two other files (i.e bc1.txt and bc2.txt) and then extract how should I modify the config file.

Thanks

**Comment by Yenaled** [comment]
Are you referring to extracting relative to bc1 and bc2 as opposed to linker1 and linker2?

If so, I recommend something like the following:

```
groups	tags	distances	locations	maxFindsG	next	minFindsG	previous
BC_1	bc1.txt$	1	0:0:9	1	{{BC_2}}8	1	-
BC_2	bc2.txt$	1	0:15	1	-	1	{{BC_1}}
```

And then you can write extract, e.g. `<sequence[4]>{{BC_2}}`, to get the 4-bp before bc2.

Essentially, this config file is saying: find bc1 (allowing one substitution) within the first 9bp's then find bc2 (allowing one substitution) somewhere at the 15th bp position or beyond (but there must be at least 8 bp's between bc1 and bc2). Only reads with a bc1 followed by a bc2 will be kept.

Caveat: I haven't tested this out, but it seems to make sense. Adjust those parameters to suit your use case.

**Comment by ashokpatowary** [comment]
Thanks @Yenaled for your quick response. The structure of my sequence looks like `ONT_Barcode1+Sequencing_Adapter1+Barcode1+Linker+Barcode2+UMI+OligoT+cDNA....+Sequencing_Adater2+ONT_Barcode2`.

Since ONT sequences are error prone so initially I want to modify the **Barcode1** and **Barcode2** sequences (if required) by comparing it to file `bc1.txt` and `bc2.txt`. Thereafter I will extract the barcode sequences based on **Sequencing_Adapter1** and **Linker**. In this scenario; from your experience what approach will be suitable with split code?

Thanks

**Comment by Yenaled** [comment]
Oof, that's a bit tricky. There are a couple of options. First option: You can error-correct the sequences by having a subs column (and putting a period . as the values in the subs column). Then you can run splitcode a second time to extract based on the linkers (like in the tutorial). Second option: You can extract the error-prone barcodes based on the linkers (like in the tutorial), then run splitcode a second time on the extracted barcodes to identify exactly what they are.

Personally, I'd probably go with option 2 because using linkers as an "anchor" is more reliable than scanning reads for a substring that resembles a barcode in your list.

Eventually, I hope to add an option that will do these things in one go (probably applying a second config on the extracted sequences).

**Comment by ashokpatowary** [comment]
Thanks @Yenaled . Looking forward to the new and updated tutorial. That will be really helpful.

**Comment by ashokpatowary** [comment]
@Yenaled apologies, reopening it as I need some information you. While correcting the barcode like the examples; is there a way to print the whole sequence; not the barcode only. Currently I am reiteration the fastqfile with 
`splitcode -c config.txt -o out.fastq --x-names --no-x-out  in.fq`
and then using barcodes reported in the comment of the new fastq files. I this way I cannot find a way to extract the corrected barcode with respect to the linker sequence.

**Comment by Yenaled** [comment]
Not sure I understand what you’re asking… can you give a simple example?

**Comment by ashokpatowary** [comment]
@Yenaled NO worries; I manage to resolved it. Thanks for your prompt response.
